sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - .pip_download_cacheA
    - "$HOME/virtualenv/python2.7.9"
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
install:
  - time make develop
script:
  - make lint
  - py.test tests
